### ISSUE TITLE
multi-database support

### ISSUE THREAD

**Issue by seanhall** [re-data/re-data#100]
**Tell us about the problem you're trying to solve**
My current production data warehouse architecture incorporates several layers of load and transformation, across several databases, over many terabytes of data (and growing). Example: my cleaning step copies data from raw sources to my 'cleaned' database, my enrichment step copies from 'cleaned' to 'enriched', and a third modeling step copies from 'enriched' to a third DB + schema for consumption. I would like to leverage re_data against all of these database/schema combinations, but the latest version of re_data is limited to reading from one database at a time. I would also like to materialize my re_data models in a dedicated database apart from my sources, but there are a number of problems with this, including:

1. This means I need to create a handful of new connection profiles in dbt profiles.yml just to run re_data queries
2. The databases configured there may be different from those in dbt_project.yml, which makes maintenance even more complicated
3. The re_data_tables model is incremental, and as such, adapts to multiple databases well. If you include schemas from multiple DBs in the re_data:schemas config, it catches them all. But the re_data_columns model is materialized as a table, so it is rebuilt on every run, and only picks up columns from the schema you've configured as both your source and destination.

Finally, I would like to be able to install and configure re_data natively to my production dbt ETL project, but due to collisions with other dbt packages, existing dbt_project.yml and profiles.yml settings and mappings, I can't do this.

**Describe the solution you’d like**
Suggested fixes include separation of source and destination, addition of database + schema var configuration, and/or incrementalize re_data_columns somehow (this would also offer schema change detection, which I believe has already been requested). Possible custom macros to generate schema and/or database mappings.

**Describe the alternative you’ve considered or used**
For now, I am maintaining three separate dbt projects separate from my primary dbt ETL project. This means three additional versions of typical dbt artifacts, and upon automation, additional layers that I need to consider in scripting container builds and commands, Airflow invocations, etc.

**Additional context**
- Snowflake user

**Comment by mateuszklimek** [comment]
@seanhall This should be solved by 0.2.1 release. Let me know if you manage to confirm that this is what you expected and it simplifies your configuration.

**Comment by mateuszklimek** [comment]
As confirmed it's working now.
