### ISSUE TITLE
[FEATURE] configure schema for metadata tables

### ISSUE THREAD

**Issue by marcin-vt** [re-data/re-data#103]
**Tell us about the problem you're trying to solve**
In our dbt project we use [generate_schema_name](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-custom-schemas#changing-the-way-dbt-generates-a-schema-name) to deploy models in multiple schemas different than the default one. Is there an easy way to set a schema for metadata tables (re_data_columns, re_data_tables)? i.e. different schema than the one defined in dbt profile.yml.

**Describe the solution you’d like**
Setting a config variable to define target schema.

**Describe the alternative you’ve considered or used**

**Additional context**
dbt: 0.20.1
re_data:  0.2.0

**Comment by mateuszklimek** [comment]
Hey @marcin-vt! You can do it by adding 
```
models:
  re_data:
    +schema:
      my_custom_schema
```

To your `dbt_project.yml` models setting. if you have any other settings in models key (most likely you have), you just add re_data key with schema there. This should also use your `generate_schema_name` marcro.

I believe config variable for it should be unnecessary (as it's natively supported by dbt).
But definitely let me know if that's what you wanted/needed :)

**Comment by marcin-vt** [comment]
Thanks for quick reply @mateuszklimek. I was trying to do what you suggested before, but only now I realized that we do discard `custom_schema_name` in `generate_schema_name`. After fixing it it works fine.

Sorry for bothering you and again thanks for help.

**Comment by mateuszklimek** [comment]
@marcin-vt No problem at all :)

Also, if you have time, it would be very helpful for me to sync a bit about how you are using (or testing) re_data.
You can pick anytime here: https://calendly.com/mateuszklimek/30min?month=2021-08  or just join our https://www.getre.io/slack and say hey to me there. Hope that works :)
