### ISSUE TITLE
[FEATURE] Make config simpler

### ISSUE THREAD

**Issue by mateuszklimek** [re-data/re-data#132]
**Tell us about the problem you're trying to solve**

Current way of configuring re_data it a bit over complicated.
re_data can be setup in 2 ways: db, code (dbt_project vars)

Going forward I think it's best to keep just one way (code configuration)
It would also make it possible to remove the need for: re_data:schemas configuration
This would also mean removing `re_data_tables` (as it would also not be needed)
`re_data_columns` would still be needed  as a intermediate store of what to monitor

**Comment by dejii** [comment]
This feature is included in this [pull request](https://github.com/re-data/dbt-re-data/pull/30). Still debating removing the model completely, not sure what the consequences are.
