### ISSUE TITLE
[FEATURE] Allow re_data configuration in model and source configs

### ISSUE THREAD

**Issue by stumelius** [re-data/re-data#163]
**Tell us about the problem you're trying to solve**

Currently there's no way of configuring monitoring for multiple models at once. It'd be convenient to be able to e.g., monitor all mart models without having to explicitly list the models in `re_data:monitored.tables` variable. 

See related 🧵 in [Slack](https://re-data.slack.com/archives/C0295HAUJHG/p1638892687021400).

**Describe the solution you’d like**

Allow re_data configuration in `dbt_project.yml` (models and sources) or `config` blocks (models only).

```
# dbt_project.yml
models:
  my_project:
    +re_data:actively_monitored: true
    staging:
      +re_data:time_filter: loaded_at
      stg_source__model_one:
        +re_data:actively_monitored: false
    marts:
      +re_data:time_filter: another_column

sources:
  source:
    +re_data:actively_monitored: true
```

```sql
-- stg_source__model_one.sql
{{ 
  config(
    re_data_actively_monitored=False, 
    re_data_time_column="loaded_at"
  )
}}

select
  *
from {{ source("source", "table_one") }}
```

**Describe the alternative you’ve considered or used**

Listing all monitored tables explicitly but that's inconvenient especially if the number of monitored models and sources is high.

**Comment by mateuszklimek** [comment]
@stumelius We deployed this one. Docs for it are available here: https://docs.getre.io/latest/docs/reference/config
Let me know your thoughts! (Super interested if that solves your problems and enables you to run re_data) 😊

**Comment by stumelius** [comment]
That's awesome @mateuszklimek ! I'll be sure to try out the latest version :)
