### ISSUE TITLE
[Improvement] Use react-table for the observability UI

### ISSUE THREAD

**Issue by dejii** [re-data/re-data#171]
**Tell us about the problem you're trying to solve**

What are you trying to do?

Currently, we have tables in the Alerts page `(pages/Alerts.tsx)` and the schema changes `(components/SchemaChanges.tsx)` tab when you view the details of a model from the lineage graph. We want to have a uniform and reusable table style for existing and new tables. Also, there's the need for the tables to have extra functionality e.g pagination, sorting, filtering etc

A clear and concise description of what you want to see happen.

[React-Table](https://react-table.tanstack.com/) lets you build and design powerful datagrid experiences while retaining 100% control over markup and styles. We think this is a good fit for the problem we're trying to solve

**Comment by akinolu52** [comment]
Nice description,

I'll work on a custom table component that can be used for existing & new table tags,
the table will contain functionalities like sorting, filtering and pagination..

**Comment by mateuszklimek** [comment]
Thanks @akinolu52, assigning this one to you! 🙂

**Comment by akinolu52** [comment]
check this [PR](https://github.com/re-data/re-data/pull/173)

**Comment by mateuszklimek** [comment]
done and deployed!
