### ISSUE TITLE
[Improvement] Make three buttons for table details static (do not scroll them)

### ISSUE THREAD

**Issue by mateuszklimek** [re-data/re-data#172]
Feedback)from the user:

> Speaking of the scroll, if you do want three buttons that change the experience at the top, it would be great to keep them visible while scrolling. Several times, I actually forgot how to see the other options because I couldn't see the top bar buttons anymore. 

Let's keep buttons mentioned static

![Screenshot 2021-12-28 at 10 58 21](https://user-images.githubusercontent.com/3945045/147556578-d27fe315-e309-490a-a3f1-daec7f7f897d.png)

**Comment by akinolu52** [comment]
I'm on it

**Comment by akinolu52** [comment]
solution is in this [PR](https://github.com/re-data/re-data/pull/173)

**Comment by mateuszklimek** [comment]
done and deployed 🎉
