### ISSUE TITLE
[FEATURE] Add dbt tests to the UI

### ISSUE THREAD

**Issue by mateuszklimek** [re-data/re-data#175]
**Tell us about the problem you're trying to solve**

We would like to visualise history of dbt tests

**Describe the solution you’d like**

Screen showing what tests have run in the past (which passed and which failed)

![Screenshot 2021-12-29 at 12 38 59](https://user-images.githubusercontent.com/3945045/147659551-e30285fd-4ae7-411c-9b0f-db93f85d96e9.png)

**Comment by akinolu52** [comment]
I'm on it

**Comment by mateuszklimek** [comment]
I will prepare test data for that.

**Comment by mateuszklimek** [comment]
@akinolu52 Schema I'm currently exporting: {'name': 'test_name' , 'status': 'Pass', 'model': 'toy_shop.customers', 'column': 'amount' }

**Comment by akinolu52** [comment]
@mateuszklimek  okay, thanks

**Comment by akinolu52** [comment]
solution [here](https://github.com/re-data/re-data/pull/189)

**Comment by mateuszklimek** [comment]
Done!
