### ISSUE TITLE
[Improvement] Redirect to alerts page

### ISSUE THREAD

**Issue by mateuszklimek** [re-data/re-data#176]
**Tell us about the problem you're trying to solve**

We would like to redirect people home page of ui to alerts page

**Comment by akinolu52** [comment]
I'm  on it

**Comment by akinolu52** [comment]
solution in this [PR](https://github.com/re-data/re-data/pull/183)

**Comment by mateuszklimek** [comment]
done & waiting for deploy in the newest release

**Comment by akinolu52** [comment]
done @mateuszklimek 
please close
