### ISSUE TITLE
[Improvement] In the UI it's not clear that clicking Details will move you to the Graph

### ISSUE THREAD

**Issue by mateuszklimek** [re-data/re-data#179]
**Tell us about the problem you're trying to solve**

Reported by the user, when in the Alerts page it's not clear to click on the Details

**Describe the solution you’d like**

Maybe we should show some kind of mini graph another option is linking to graph from table_name column

**Comment by akinolu52** [comment]
@mateuszklimek  i think i like the other option, where you link to the graph page from the table_name column

so can i implement the second option?

**Comment by mateuszklimek** [comment]
@akinolu52 yeah, sounds good  👍

**Comment by akinolu52** [comment]
@mateuszklimek this fix is in this [PR](https://github.com/re-data/re-data/pull/185)

**Comment by mateuszklimek** [comment]
done!
