### ISSUE TITLE
[FEATURE] Table view

### ISSUE THREAD

**Issue by mateuszklimek** [re-data/re-data#186]
**Tell us about the problem you're trying to solve**

We would like to have a page, showing information about specific table:
Something similar to that:

![Screenshot 2022-01-04 at 12 52 14](https://user-images.githubusercontent.com/3945045/148055485-ff606e4b-420f-4b78-92a0-3f75b110e1e2.png)

**Comment by akinolu52** [comment]
i'm on it ☺️

**Comment by mateuszklimek** [comment]
👍

**Comment by akinolu52** [comment]
solution [here](https://github.com/re-data/re-data/pull/189)

**Comment by akinolu52** [comment]
done @mateuszklimek 
please close
