### ISSUE TITLE
[FEATURE] refactor logic for generating alert messages

### ISSUE THREAD

**Issue by dejii** [re-data/re-data#191]
**Tell us about the problem you're trying to solve**
The columns in the alert page are currently formatted on the client side to generate the message for anomalies and schema changes. The same message needs to be generated for the slack notification feature and we won't want to duplicate the logic. 

What are you trying to do?
Move the logic for generating the message to the dbt-re-data package and refactor the client side application to just display the already generated message.

**Comment by akinolu52** [comment]
I’m on it
