### ISSUE TITLE
[DOCUMENTATION] - List of Metrics

### ISSUE THREAD

**Issue by KarmitoHerry** [re-data/re-data#202]
Hi re_data team!

I want to suggest about indent on list metrics on right side in this url : https://docs.getre.io/latest/docs/reference/data_monitoring/metrics

like this attachement on the red box: 
<img width="251" alt="Screen Shot 2022-01-26 at 15 28 12" src="https://user-images.githubusercontent.com/10266075/151130930-86b8dd27-9791-4f24-b467-5f4758ce567c.png">

Reason : If developer doesn't carefully about the Capital Character in each metric , we can miss understanding the usage of the metric.

Thank you

**Comment by mateuszklimek** [comment]
@KarmitoHerry this will be solved with the next release, check out new docs yet: https://docs.getre.io/feature-dbt-config-support/docs/reference/metrics/base_metrics (not released yet)

**Comment by mateuszklimek** [comment]
Done in 0.6.0 release
