### ISSUE TITLE
[FEATURE - Show just monitored nodes]

### ISSUE THREAD

**Issue by aambrosi** [re-data/re-data#212]
Hi re_data team!

what I would like to see using re_data UI would be a graph showing just nodes that are specified in dbt_project as monitored.

What I suggest would be a a switch to show only monitored nodes or all nodes. 

Thank you!

**Comment by akinolu52** [comment]
hi @aambrosi please upgrade to the latest version. 
We've this feature on the graph screen of the lastest version.
can you please close this issue?
