### ISSUE TITLE
[FEATURE - UI improvement]

### ISSUE THREAD

**Issue by aambrosi** [re-data/re-data#216]
**Tell us about the problem you're trying to solve**

Hi all, 

- I would like to suggest having the possibility to show or hide a category of items in the graph by clicking on these category buttons.

> ![image](https://user-images.githubusercontent.com/19605518/152570054-14f74092-e73b-47b1-95b3-10290b6a2d28.png)

- Also, another feature that in my case would improve the usability (since we have a lot of nodes) would be the possibility to find nodes by using CTRL+F on the graph page.

- [FIXED] Lastly (but not sure this is the right place cause it might be a bug) in the following section where to search for a table, it is not possible to enter - or _ characters nor to go backwards with <- arrow on the keyboard to go back when typing a table name.

> ![image](https://user-images.githubusercontent.com/19605518/152570924-262038ea-4773-4880-ba6d-f8e5be60ea2a.png)

**Comment by aambrosi** [comment]
Resolved the 3rd point thanks to 0.6.1. Thanks @mateuszklimek !

**Comment by akinolu52** [comment]
@aambrosi pls close the issue as it has been resolved, thanks
