### ISSUE TITLE
[FEATURE] customizable target for storing generated artefacts 

### ISSUE THREAD

**Issue by dejii** [re-data/re-data#236]
**Describe the bug**
Currently when re_data generates files, they are stored by default in the `target/re_data/` folder. But `target-path:` might contain a path other than `'target/'`. When the `target/` folder is unaccessible due to maybe permission issues for example, generating overview would cause an error.

**Expected behavior**
re_data should be able to read the `target-path` from the dbt-project.yml file or even accept `--re-data-target-dir` as an argument. 

If `--re-data-target-dir` isn't passed as an argument, we default to using the `target-path` in dbt_project.yml to store files generated

**Comment by mateuszklimek** [comment]
Done!
