### ISSUE TITLE
[FEATURE] Support `--vars` option as dbt provides

### ISSUE THREAD

**Issue by yu-iskw** [re-data/re-data#242]
**Tell us about the problem you're trying to solve**

What are you trying to do?
We dynamically set destination databases (projects on BigQuery) of dbt models by passing variables based on the environment. For instance, when we run dbt in the QA environments, we pass the variables corresponding to it.

At the moment, re-data  CLI doesn't support the option to pass variables as dbt's `--vars` option. So, we can't run re-data on our dbt project.

```
$ re_data overview generate --start-date 2022-01-01 --end-date 2022-01-30 --interval days:1
dbt run-operation generate_overview --args end_date: '2022-01-30'
interval: days:1
start_date: '2022-01-01'

07:39:20  Running with dbt=1.0.3
07:39:20  Unable to do partial parsing because of a dbt version mismatch. Saved manifest version: 1.0.1. Current version: 1.0.3.
07:39:24  Encountered an error:
Parsing Error in model xxxxxxxx (models/xxxx/xxxxxxxx/xxxx.sql)
  at path ['database']: Undefined is not valid under any of the given schemas
Traceback (most recent call last):
  File "/Users/yu/anaconda2/envs/dwh-dbt/bin/re_data", line 8, in <module>
    sys.exit(main())
  File "/Users/yu/anaconda2/envs/dwh-dbt/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/yu/anaconda2/envs/dwh-dbt/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/yu/anaconda2/envs/dwh-dbt/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/yu/anaconda2/envs/dwh-dbt/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/yu/anaconda2/envs/dwh-dbt/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/yu/anaconda2/envs/dwh-dbt/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/yu/anaconda2/envs/dwh-dbt/lib/python3.8/site-packages/re_data/command_line.py", line 230, in generate
    completed_process.check_returncode()
  File "/Users/yu/anaconda2/envs/dwh-dbt/lib/python3.8/subprocess.py", line 448, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['dbt', 'run-operation', 'generate_overview', '--args', "end_date: '2022-01-30'\ninterval: days:1\nstart_date: '2022-01-01'\n"]' returned non-zero exit status 2.
```

### Example of what we do
We pass variables to pass GCP projects based on the environments as QA and production, using `--vars`.

```bash
dbt run --vars "$(cat ./config/vars-qa.yml)"
```

Those are examples of YAML files to manage GCP project.
```yaml
# vars-qa.yaml
projects:
  project-a: "project-a-staging"
  project-b: "project-b-staging"

# vars-production.yaml
projects:
  project-a: "project-a-production"
  project-b: "project-b-production"
```

That below is an example to dynamically settle the destination GCP project.
```sql
{% set gcp_project = var('projects')['dev_project_id']|default(var('projects')['project-a'], True) %}

{{
  config(
    materialized="table",
    database=gcp_project,
    schema="sample_dataset",
  )
}}

SELECT ...
```

**Describe the solution you’d like**

A clear and concise description of what you want to see happen.

The best solution for us is re-data CLI supports the `--vars` options.

**Describe the alternative you’ve considered or used**

**Comment by dejii** [comment]
Hi @yu-iskw , thanks for bringing this to our attention. We are working on a fix to accept `--dbt-vars` as an argument which would be passed down as vars to dbt commands.

**Comment by yu-iskw** [comment]
@dejii Thank you for addressing the issue. I look forward to the updates. Please let me know, if there is anything I can help.

**Comment by mateuszklimek** [comment]
@yu-iskw Passing dbt-vars is possible now, you can check re_data docs for details: https://docs.getre.io/latest/docs/reference/cli/overview :)

**Comment by yu-iskw** [comment]
@mateuszklimek Thank you for letting me know. I will give it a try.

**Comment by yu-iskw** [comment]
@mateuszklimek Sorry for the delay of updates. I tried out the `--dbt-vars` option. In our case, I face with an issue on the return code of `dbt docs generate` with `re_data overview generate`. I have created the issue and the pull request. Please take a look?

- https://github.com/re-data/re-data/issues/308
- https://github.com/re-data/re-data/pull/309
