### ISSUE TITLE
[BUG] Can't open 'lineage' and 'tables' pages

### ISSUE THREAD

**Issue by JustasGrinaveckis** [re-data/re-data#247]
**Describe the bug**
Can't open 'lineage' and 'tables' (after selecting certain tables) pages.

**Expected behavior**
One should be able to open these pages 

**To Reproduce**
 run command in terminal 're_data overview serve', navigate to page 'lineage'

**Screenshots**

![Screenshot 2022-03-18 at 15 29 03](https://user-images.githubusercontent.com/91603008/159012372-ba20de85-0193-4fdf-bf01-580fcdc9e829.png)

**Logs and additional context**
If application, any other context, logs etc.here

**Comment by mateuszklimek** [comment]
Hey @JustasGrinaveckis  thanks for reporting this, will you have 15 minutes to jump on a quick call with us to investigate the issue?

**Comment by akinolu52** [comment]
Hi @JustasGrinaveckis 

Are you available for a quick call via google meet?

**Comment by JustasGrinaveckis** [comment]
@mateuszklimek very sorry for delayed response - of course I can, whenever you have time.

**Comment by mateuszklimek** [comment]
@JustasGrinaveckis Thanks for the time, we found an issue and will be releasing the fix today, will keep you posted :) Thanks for reporting that!
