### ISSUE TITLE
[BUG] 'dbt.contracts.graph.compiled.CompiledSingularTestNode object' has no attribute 'test_metadata'

### ISSUE THREAD

**Issue by joshuataylor** [re-data/re-data#254]
**Describe the bug**
Adding the snippet from https://docs.getre.io/latest/docs/reference/tests/history
```
on-run-end:
  - "{{ re_data.save_test_history(results) }}"
```

Shows an error at the end of the test run:
```
02:27:54  Running 1 on-run-end hook
02:27:54  Database error while running on-run-end
02:27:54  Encountered an error:
Compilation Error in operation xxx_dwh-on-run-end-0 (./dbt_project.yml)
  'dbt.contracts.graph.compiled.CompiledSingularTestNode object' has no attribute 'test_metadata'

  > in macro save_test_history (macros/run_end/save_results_history.sql)
  > called by operation xxx_dwh-on-run-end-0 (./dbt_project.yml)
```

**Expected behavior**
It works?

**To Reproduce**
Not sure, happens with dbt 1.0.4 and Snowflake (but I don't think it's a a Snowflake issue).

**Comment by mateuszklimek** [comment]
@joshuataylor Hey, thanks for reporting that. It looks like we don't handle tests that don't have a model connected to them properly.

Working on the fix now. I wonder how much is this issue blocking you from implementing re_data? (we should have a fix next week, but can try to make it faster if that's critical)

**Comment by joshuataylor** [comment]
We have it running with our normal models and it's working great, this is for tests. No rush!

**Comment by mateuszklimek** [comment]
Hey @joshuataylor, we recently realised the new re_data version and this problem should be solved there. Also, there is a bit similar setup for making re_data store tests history. You can check it here: https://docs.getre.io/latest/docs/reference/tests/history
