### ISSUE TITLE
[FEATURE] Add search for lineage graph view

### ISSUE THREAD

**Issue by mateuszklimek** [re-data/re-data#281]
**Tell us about the problem you're trying to solve**

With bigger number of nodes it's quite hard to find a specific node in the graph.
Search which would solve this problem.

![Screenshot 2022-05-08 at 14 43 53](https://user-images.githubusercontent.com/3945045/167296742-83b2d5a0-1bb7-431a-b8bd-381ba295f43e.png)

**Comment by mateuszklimek** [comment]
Description of the problem https://petrjanda.substack.com/p/untapped-potential-of-data-lineage?s=w

**Comment by akinolu52** [comment]
okay
