### ISSUE TITLE
[FEATURE] re_data:select support for tag selection

### ISSUE THREAD

**Issue by VasiliiSurov** [re-data/re-data#317]
**Tell us about the problem you're trying to solve**

We are running large dbt mono-repository with multiple sub-domains that are separated by tags. All these individual domains are running on different schedule and model related metrics should be available as soon as possible. I want to calculate metrics for a dynamically defined subset of models using `re_data:select` using dbt tags 

**Describe the solution you’d like**

I want re_data package to support all or some of the dbt selector functionality  [Specifying resources](https://docs.getdbt.com/reference/node-selection/syntax#specifying-resources), as a bare minimum select nodes by tag to run.
Additional constraint, selector resolution must be implemented inside dbt so everybody can leverage it (dbt Cloud allows to execute only `dbt ...` commands)

**Describe the alternative you’ve considered or used**

No good solution

**Comment by mateuszklimek** [comment]
@VasiliiSurov  This should be solved by the new release today! :) Let me know if you have any further thoughts or issues on what we can improve! :)
