### ISSUE TITLE
[BUG] - re_internal_re_data_last_base_metrics_thread1 fails

### ISSUE THREAD

**Issue by alaturqua** [re-data/re-data#318]
**Describe the bug**
Running re_data overview generate fails.

**Expected behavior**
Run should pass

**To Reproduce**
 re_data overview generate

**Screenshots**

**Logs and additional context**

Receiving following error:
```
22:08:55  16 of 27 ERROR creating table model re_internal.re_data_last_base_metrics_thread1  [ERROR in 1.05s]
22:09:05  Database Error in model re_data_last_base_metrics_thread1 (models/internal/metrics/base/re_data_last_base_metrics_thread1.sql)
22:09:05    001044 (42P13): SQL compilation error: error line 824 at position 4
22:09:05    Invalid argument types for function 'DATE_DIFFTIMESTAMPINSECONDS': (NUMBER(38,0), TIMESTAMP_NTZ(9))
```
If application, any other context, logs etc.here

**Comment by mateuszklimek** [comment]
Hey @alaturqua as per discussion in the slack: [🧵](https://re-data.slack.com/archives/C0295HAUJHG/p1656921473147329) I assume we can close this one correct?
