### ISSUE TITLE
[BUG] UI error when tests_history.json contains generic tests

### ISSUE THREAD

**Issue by miro-ur** [re-data/re-data#330]
**Describe the bug**
When dbt project contains generic tests (standalone sql tests - not linked to a column) the `table_name` and `column_name` columns are `null` in the `re_data_test_history` table. This causes a issue in the UI - nothing will render (across the entire app) because the `tests_history.json` will contain mix of string and **null** values in the `table_name` and `column_name` attributes.

**Expected behavior**
I would expect to be able to show both column tests as well as generic tests and UI be able to handle null values in json - specially if the attribute is optional by definition. Risk here is that one unexpected value in any input json file (while being valid json) will render the whole UI useless.

**To Reproduce**
Create and run generic test with `re_data:save_test_history: true` and try to show re_data overview.

**Screenshots**
![screen_capture_20220719_003](https://user-images.githubusercontent.com/20729127/179846348-26b3359c-fe67-4c88-94f5-9b1ed55f49fd.png)

**Comment by mateuszklimek** [comment]
@miro-ur  This should be solved by the new release today! :) Let me know if you have any further thoughts or issues!
