### ISSUE TITLE
[BUG] Fix typo in 'All Good!🎉' slack alert

### ISSUE THREAD

**Issue by c0nn0rstevens** [re-data/re-data#340]
**Describe the bug**
The alert says 're_data did found any alerts at the moment' when it should say 're_data didn't find any alerts at the moment'.

**Expected behavior**
slack message should say 're_data didn't find any alerts at the moment'.

**To Reproduce**
Run `re_data overview serve` for a run with no failed tests, anomalies or schema changes while slack notifications are setup.
**Screenshots**
![Screenshot 2022-08-12 at 14 42 40](https://user-images.githubusercontent.com/72092369/184357819-67257612-08dc-4c2c-9408-fad6c5d2f881.png)

**Logs and additional context**
None.

**Comment by mateuszklimek** [comment]
@c0nn0rstevens This one is merged so solving the issue here 🎉
