### ISSUE TITLE
UI is not available (blank) when using generic test [BUG]

### ISSUE THREAD

**Issue by OhadSrur** [re-data/re-data#358]
**Describe the bug**
When using a generic test in dbt (read more [here](https://docs.getdbt.com/guides/legacy/writing-custom-generic-tests)), the process that creates the `tests_history.json` file, assign `null` value to `table_name` attribute. Which causes the UI to break.

**Expected behavior**
The UI should work regardless of the null value in the table_name attribute.

**To Reproduce**
Add the object below to your `tests_history.json` file, and run `re_data overview serve` to see results

```
{
    "table_name": null,
    "column_name": null,
    "test_name": "breaking_test",
    "run_at": "2022-09-23T20:08:51",
    "status": "Pass",
    "execution_time": 8.718281269073486,
    "message": null,
    "failures_count": 0.0,
    "failures_json": "",
    "failures_table": null,
    "severity": "ERROR",
    "compiled_sql": ""
}
```

**Comment by akinolu52** [comment]
@OhadSrur thanks for the observation, we'll be deploying an update to this soon. thanks
