### ISSUE TITLE
Can't install re_cloud due to old version of jsonschema package used

### ISSUE THREAD

**Issue by moseleyi** [re-data/re-data#384]
**Describe the bug**
Can't install `re_cloud`

**Expected behavior**
`re_could` gets intalled

**To Reproduce**
`pip install re_cloud`

**Screenshots**
![image](https://user-images.githubusercontent.com/16131590/214018196-696ed713-c4ac-4888-b0f1-4a108066e5ad.png)

**Logs and additional context**
It looks like it uses an outdated version of a package `jsonschema`. I don't really want to downgrade this package as it may be used by dbt or other tools installed. Is there any workaround here?

**Comment by mateuszklimek** [comment]
Hey @moseleyi I see you solved the issue, is it that it's now happening any more?
