### ISSUE TITLE
[FEATURE] dbt-core v1.4.0 support

### ISSUE THREAD

**Issue by nicoekkart** [re-data/re-data#387]
**Tell us about the problem you're trying to solve**

Use re-data together with dbt-bigquery/dbt-core v1.4.0

**Describe the solution you’d like**

I think the requirements just have to allow this. I don't know if there are specific things that could break with this upgrade?

**Describe the alternative you’ve considered or used**

Keep using dbt adapters <1.4.0

**Comment by fadi-circleci** [comment]
There's a security issue in the cryptography package which should be upgraded to v38.0.3 to fix it. Unfortunately, dbt-core 1.4 is the only version compatible with that version of cryptography. 

Therefore using re_data blocks patching a security vuln requiring you to remove it.

**Comment by mateuszklimek** [comment]
Hye @fadi-circleci @nicoekkart, sorry for the slow reaction here. I will be testing re_data with dbt 1.4 asap, to fix this issue.

**Comment by fadi-circleci** [comment]
Thanks for advancing this.
The funny thing is we now need to advance to cryptography 39.0.0 which requires 1.5.x(1.5.0a1) dbt-core and dbt-snowflake preleases.

**Comment by mateuszklimek** [comment]
@fadi-circleci Oh, that's a pity. I can probably do some alfa release or just a branch (to install from it) which allows dbt 1.5.x. One thing is, it's not in PyPI yet, so not sure how stable it would be (I think you would need to install it from dbt github master, I assume?)

**Comment by fadi-circleci** [comment]
I dont think dbt-core has wheels built for nightly release of 1.5.x.

**Comment by fadi-circleci** [comment]
@mateuszklimek dbt-core 1.5.0b1 is on pypi. Do you think we can get the upper bound increased to allow this?

**Comment by mateuszklimek** [comment]
Hey @fadi-circleci I've relased beta version of re_data which allows this version of dbt, it's here: https://pypi.org/project/re-data/0.10.8b1/.
One thing about it, you will get an alert about not matching dbt python packages, but as they were not other changes added to the release this should work fine.

**Comment by davidzajac1** [comment]
The release of 0.10.9 supports up to dbt-core 1.7, closing this issue.

https://github.com/re-data/dbt-re-data/releases/tag/0.10.9
