### ISSUE TITLE
[BUG] save_test_history macro doesn't store compiled_sql after dbt-core>=v1.3.0

### ISSUE THREAD

**Issue by gh-pankaj** [re-data/re-data#397]
**Describe the bug**
The `save_test_history` macro stores `compiled_sql` as null when used with `dbt-core>=v1.3.0`. This is because the `compiled_sql` field in node has been renamed to `compiled_code` since `dbt-core>=v1.3.0`(i.e. after release of python models)

**Expected behavior**
The `save_test_history` macro should store `compiled_sql` irrespective of dbt version. 

**To Reproduce**
- Install the `re_data` dbt package (version [">=0.10.0", "<0.11.0"]) on a dbt project with `dbt-core>=v1.3.0`
- Run tests on models, sources or seeds (with `re_data_monitored: true` config) 
- Check `re_data_test_history` table in your target database, or look at `Compiled SQL` tab on your re_data overview site. You will see no compiled sql available.

**Screenshots**
<img width="934" alt="image" src="https://user-images.githubusercontent.com/93124714/236464383-6f287e15-ab47-4935-9d3d-01cb844c2583.png">

**Logs and additional context**

**Comment by davidzajac1** [comment]
Fixed by: https://github.com/re-data/dbt-re-data/pull/113
