### ISSUE TITLE
[FEATURE]Support booleans and add count_true and count_false metrics for booleans

### ISSUE THREAD

**Issue by suelai** [re-data/re-data#405]
**Tell us about the problem you're trying to solve**

Get counts of `TRUE` and `FALSE` for boolean values. Right now the column type are text and numeric only

**Describe the solution you’d like**

change the macros that detect the column types per each adapter to recognise booleans and add two metrics of `count_true` and `count_false`

**Describe the alternative you’ve considered or used**
I have implemented this solution by overriding the macro `bigquery__get_column_type` in my project and creating two custom metrics. I would like to add my solution for BigQuery upstream.

**Comment by davidzajac1** [comment]
Fixed by [re-data/dbt-re-data](https://github.com/re-data/dbt-re-data/pull/118), closing
