### ISSUE TITLE
Asynchronous data source import

### ISSUE THREAD

**Issue by hishoss** [re-data/re-data#87]
**Tell us about the problem you're trying to solve**
Adding a new data source with several tables can take so much time on the data source view within the web UI, due to redata importing and configuring tables from the source.

**Describe the solution you’d like**
Make this table import a task queue using for eg. [celery](https://docs.celeryproject.org/en/stable/getting-started/introduction.html)

I think the function to convert into an async task is the `redata.checks.data_schema.check_for_new_tables` which is used by `redata.ui_admin.data_source.DataSourceView` to import the data source from the ui.

**Comment by mateuszklimek** [comment]
@hishoss Good point. One thing regarding celery, there actually already is asynchronous mechanism for running those checks in Redata - airflow. So I think using it maybe best, just one thing is we would need to find a way to trigger airflow job when datasource it added (it seems like quite standard operation, but I wasn't sure how to do it properly in airflow).

And actually solving those (triggering airflow job) would be also useful when doing custom scan, it would enable us to remove pulling approach (every minute) currently used.. :)

**Comment by hishoss** [comment]
Good point @mateuszklimek. Running a data source import as an airflow job looks like the best way to go. I'll dig in the code to understand the minute jobs then we can plan on how best to refactor that process.

**Comment by mateuszklimek** [comment]
👍

**Comment by mateuszklimek** [comment]
After switch to dbt based packge it's no longer actual
