### ISSUE TITLE
Add Kubernetes support

### ISSUE THREAD

**Issue by mateuszklimek** [re-data/re-data#9]

**Comment by arviCV** [comment]
Hi,
Is someone working on this issue?
Can you please elaborate more on the specifics.

**Comment by mateuszklimek** [comment]
@arviCV  Let me check because one person was interested in working on it. 

Overall idea is to have a similar setup to one via docker-compose but done with Kubernetes. It can be only for development/single cluster for now, but an idea is in the end to have something easily deployable on Google Kubernetes Engine/Amazon Elastic Kubernetes Service.

**Comment by mateuszklimek** [comment]
Doesn't apply anyore
