### ISSUE TITLE
[FEATURE] Notify on Slack (other channels?) about new anomalies

### ISSUE THREAD

**Issue by mateuszklimek** [re-data/re-data#94]
**Tell us about the problem you're trying to solve**

Saving anomalies is great for analysis, but for quick response, it would be good to have a notification system for them

**Describe the solution you’d like**

It would be great if re_data notifies you on Slack/other channels? of new anomalies found.

**Comment by KarmitoHerry** [comment]
Can we have notification/alert on emails on `re_data`?

I think if some companies doesn't us slack as main communications app.

**Comment by mateuszklimek** [comment]
@KarmitoHerry, thanks for suggesting. I think we will do a separate issue for this, and I agree it would be really good to add.

**Comment by dejii** [comment]
@KarmitoHerry just curious, what email delivery provider do you use if you can share?

**Comment by KarmitoHerry** [comment]
> 

On my company , we are using g-suite for operational thing. But we have backup mail server for other use.
But on daily basis, we use open-source chat app : mattermost

**Comment by mateuszklimek** [comment]
@KarmitoHerry We definitely would like to support email for notifications as well, thanks for your input on the setup.
If you would like to create an issue for email support it would be great.
As this issue was about Slack integration I'm closing it as done 😊
